% First, initialize the values needed in this program.
r1 = input('R1:'); % Stator resistance
x1 = input('X1:'); % Stator reactance
r2 = input('R2:'); % Rotor resistance
x2 = input('X2:'); % Rotor reactance
xm = input('XM:'); % Magnetization branch reactance
Vt = input('Vt:'); % Total voltage
Vr = Vt * 5/6; % Total voltage
v_phase = Vr / sqrt(3) % V phase
P = input('P:'); % Number of poles
s = input('s:'); % Slip
n_sync = (120*50)/P  % Synchronous speed (r/min)
w_sync = n_sync*2*pi/60% Synchronous speed (rad/s)
nm = (1 - s) * n_sync % Mechanical speed
Z2 = r2/s + j*x2 % Secondary side
ZF = 1/(-1/xm*j + 1/Z2) % Combined magentization plus rotor impedance
r=abs(ZF)
rangle = phase(ZF)
Ia = v_phase/(r_th)
ia = abs (Ia)
iaangle = phase(Ia) 
Pscl = 3*ia^2*r1 % Stator copper loss
Pag = 3*ia^2*r % Air gap power
Pconv = (1-s)*Pag % Converted power
Tind = Pconv/w_sync % Induced torque in motor
Pout = Pconv - 800 - 600 - 298.4 % Power output
w_m = nm*2*pi/60 % Synchronous speed (rad/s)
Tload = Pout/w_m % Load torque
Pin = 3*v_phase*ia*cos(iaangle) % Power input
n = Pout / Pin *100 % Efficiency